# se puede usar "REST Client" en VSC para usar este archivo 

# CREAR USUARIO
POST http://127.0.0.1:8000/users/ 
Content-Type: application/json

{ "username": "user1", "password": "admin" }


###
# AUTENTICACION
POST http://127.0.0.1:8000/token/
Content-Type: application/json

{ "username": "Turko", "password": "admin" }


###
# CREAR TAREA
POST http://127.0.0.1:8000/tasks/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEwOTUwODIxLCJpYXQiOjE3MTA5NDgxMjEsImp0aSI6IjIzZDlhMDM4MjNhZDQzNDBiMmFkZGMwNTdhZGIxZWE2IiwidXNlcl9pZCI6Mn0.wEm2x1-gPBiFyGbNckv895OyGTROCLrcl0GQ1pSr10s

{
    "title": "Añadir tarea #4",
    "description": "Tarea registrada con REST client"
}


###
# LISTAR TAREAS 
GET http://127.0.0.1:8000/tasks/

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEwOTUzMTA2LCJpYXQiOjE3MTA5NTA0MDYsImp0aSI6ImVmYTEwODA2MDE4OTQ0Yzg5ZDJlNzg0MmViYzQzMTBmIiwidXNlcl9pZCI6Mn0.WcAB_dY_rnC4x0ASDxfwNaJa1dSHqupEmwDIh4uLrOo


###
# FILTRAR TAREAS POR TITULO,DESCRIPCION Y FECHA
GET http://127.0.0.1:8000/tasks/?query=&date=2024-03-05
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEwOTUwODgzLCJpYXQiOjE3MTA5NDgxODMsImp0aSI6IjU2N2NhMTkzNjNmMDRiMjI4NGI4OGEwOTc4ZTNmNTI2IiwidXNlcl9pZCI6Mn0.sX8gAwQeMQ9QfLsgXyR7O1Fh0ebQ46jvmrW8PP-k2Qk

